export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_START = "FETCH_ARTICLES_START";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAIL = "FETCH_ARTICLES_FAIL";

export const FETCH_ARTICLES_FILTERS = "FETCH_ARTICLES_FILTERS";
export const FETCH_ARTICLES_FILTERS_START = "FETCH_ARTICLES_FILTERS_START";
export const FETCH_ARTICLES_FILTERS_SUCCESS = "FETCH_ARTICLES_FILTERS_SUCCESS";
export const FETCH_ARTICLES_FILTERS_FAIL = "FETCH_ARTICLES_FILTERS_FAIL";

export const DROPDOWN_CONTENT = "DROPDOWN_CONTENT";
export const CLEAR_BUTTON = "CLEAR_BUTTON";

export const GET_ARTICLE_ID = "GET_ARTICLE_ID";
